apply plugin: 'com.android.library'

android {
    namespace 'dk.ternedal.skyplayer.engine.androidlib'
    compileSdk 34

    ndkVersion "27.2.12479018"
    def unityEditor = System.getenv("UNITY_EDITOR_PATH")
    def resolvedNdk = System.getenv("ANDROID_NDK_ROOT") ?:
                      (unityEditor ? "${unityEditor}/Data/PlaybackEngines/AndroidPlayer/NDK" : null)
    if (resolvedNdk != null) {
        ndkPath resolvedNdk
    }

    defaultConfig {
        minSdk 29
        externalNativeBuild {
            cmake {
                arguments "-DANDROID_STL=c++_shared"
                cppFlags "-std=c++14"
            }
        }
    }

    externalNativeBuild {
        cmake {
            path "src/main/cpp/CMakeLists.txt"
            version "3.22.1"
        }
    }
}

dependencies {
    implementation 'androidx.media3:media3-exoplayer:1.4.1'
    implementation 'androidx.media3:media3-datasource:1.4.1'
    implementation 'androidx.media3:media3-common:1.4.1'
}
